# This workflow deploys a storage account to Azurecccc

name: Run Powershell Scripts

# Controls where the Workflow will run
on:
  workflow_dispatch: 

jobs:
  run-powershell:
    name: Using Azure Sql Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create db from file.ps1
        run: ./createdb.ps1
        shell: pwsh
