# This workflow deploys a storage account to Azurecccc

name: DeployToAzure

# Controls where the Workflow will run
on:
  workflow_dispatch: 

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Start Db crreate from file.ps1
        shell: pwsh
        run: |
          createdb.ps1
